#!/bin/bash
### BEGIN INIT INFO
# Provides:          servoblaster
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO

# sudo motion -c /home/pi/motion/motion-mmalcam.conf
SCRIPT=motion 
CONFIG=/home/pi/motion/motion-mmalcam.conf
COMMAND="$SCRIPT -c $CONFIG"

start(){
	$COMMAND &
	sleep 1
	PID=$(ps aux | grep -v grep|grep $SCRIPT |awk '{print $2}') # get PID
	echo "script started with pid:" $PID
}

stop(){
	PID=$(ps aux | grep -v grep|grep $SCRIPT |awk '{print $2}') # get PID
	kill -15 $PID
	echo "killed" $SCRIPT "with pid:" $PID
}

case "$1" in 
	start)
 		echo "Starting " $SCRIPT
       		start
        	;;
	stop)
       		echo "Stopping " $SCRIPT
		stop
        	;;

	restart)
		stop
		start
		;;
    	*)
       		 echo "Usage: /etc/init.d/servod start|stop"
        	exit 1
        ;;
esac

exit 0
